version: '3'
services:
  fastapi-practice:
    build: .
    volumes:
      - .dockervenv:/src/.venv
      - .:/src
    ports:
      - 8000:8000 # ホストマシンのポート8000を、docker内のポート8000に接続する(Connect the port 8000 of host machine to port 8000 that in Docker)

